
package csc.integral.cp.face.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InterfacewebServiceManager", targetNamespace = "http://webservice.face.cp.integral.csc/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface InterfacewebServiceManager {


    /**
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String process(
        @WebParam(name = "data", partName = "data")
        String data);

}
