
package csc.integral.cp.face.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InterfaceWebService", targetNamespace = "http://webservice.face.cp.integral.csc/", wsdlLocation = "http://10.1.5.192:8001/services/InterfaceWebService?wsdl")
public class InterfaceWebService
    extends Service
{

    private final static URL INTERFACEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTERFACEWEBSERVICE_EXCEPTION;
    private final static QName INTERFACEWEBSERVICE_QNAME = new QName("http://webservice.face.cp.integral.csc/", "InterfaceWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.5.192:8001/services/InterfaceWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTERFACEWEBSERVICE_WSDL_LOCATION = url;
        INTERFACEWEBSERVICE_EXCEPTION = e;
    }

    public InterfaceWebService() {
        super(__getWsdlLocation(), INTERFACEWEBSERVICE_QNAME);
    }

    public InterfaceWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTERFACEWEBSERVICE_QNAME, features);
    }

    public InterfaceWebService(URL wsdlLocation) {
        super(wsdlLocation, INTERFACEWEBSERVICE_QNAME);
    }

    public InterfaceWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTERFACEWEBSERVICE_QNAME, features);
    }

    public InterfaceWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterfaceWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InterfacewebServiceManager
     */
    @WebEndpoint(name = "InterfacewebServiceManagerImplPort")
    public InterfacewebServiceManager getInterfacewebServiceManagerImplPort() {
        return super.getPort(new QName("http://webservice.face.cp.integral.csc/", "InterfacewebServiceManagerImplPort"), InterfacewebServiceManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterfacewebServiceManager
     */
    @WebEndpoint(name = "InterfacewebServiceManagerImplPort")
    public InterfacewebServiceManager getInterfacewebServiceManagerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.face.cp.integral.csc/", "InterfacewebServiceManagerImplPort"), InterfacewebServiceManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTERFACEWEBSERVICE_EXCEPTION!= null) {
            throw INTERFACEWEBSERVICE_EXCEPTION;
        }
        return INTERFACEWEBSERVICE_WSDL_LOCATION;
    }

}
